### ISSUE TITLE
Facter collection

### ISSUE THREAD

**Issue by archspangler** [domeger/SplunkTAforPuppetEnterprise#8]
Does the TA need to be installed on the Puppet Enterprise server or can it be installed on any HF?
You still have enabled IP's/hostnames in the ../default/inputs.conf??

Here is my input and the log entries for factor collection.

[puppet_enterprise_factors://PuppetEnterpriseFactors_prod]
environment = production
index = unix
interval = 300
port_ = 8081
puppet_enterprise_server_ = xxx.xxx.xxx
server_ = https://xxx.xxx.xxx
token_ = ********
token_generation_date_ = 09/22/18

logs..
2018-09-23 09:39:21,016 INFO pid=14523 tid=MainThread file=connectionpool.py:_new_conn:758 | Starting new HTTPS connection (1): 127.0.0.1
2018-09-23 09:39:22,303 INFO pid=14523 tid=MainThread file=connectionpool.py:_new_conn:758 | Starting new HTTPS connection (1): 127.0.0.1
2018-09-23 09:39:24,035 INFO pid=14523 tid=MainThread file=connectionpool.py:_new_conn:758 | Starting new HTTPS connection (1): 127.0.0.1
2018-09-23 09:39:26,077 INFO pid=14523 tid=MainThread file=setup_util.py:log_info:114 | Log level is not set, use default INFO
2018-09-23 09:39:26,078 INFO pid=14523 tid=MainThread file=setup_util.py:log_info:114 | Customized key can not be found
2018-09-23 09:39:26,078 ERROR pid=14523 tid=MainThread file=base_modinput.py:log_error:307 | Get error when collecting events.
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SplunkTAforPuppetEnterprise/bin/splunktaforpuppetenterprise/modinput_wrapper/base_modinput.py", line 127, in stream_events
    self.collect_events(ew)
  File "/opt/splunk/etc/apps/SplunkTAforPuppetEnterprise/bin/puppet_enterprise_factors.py", line 84, in collect_events
    input_module.collect_events(self, ew)
  File "/opt/splunk/etc/apps/SplunkTAforPuppetEnterprise/bin/input_module_puppet_enterprise_factors.py", line 63, in collect_events
    if pe_link:
NameError: global name 'pe_link' is not defined

**Comment by domeger** [comment]
This TA has been tested on a separate box, without any Puppet Enterprise Agent, I have rolled this TA on the last three released on Puppet Enterprise. Did you remove all the inputs and recreated them?

**Comment by domeger** [comment]
Just fixed this part, pull the latest version and this issues should be resolved now.

**Comment by archspangler** [comment]
That worked for me.  I will close this issue.
